### ISSUE TITLE
Suggestion: filter out nodes running outdated versions 

### ISSUE THREAD

**Issue by j-berman** [lalanza808/monero.fail#11]
A few of the nodes on the site seem to still be running the outdated fork. You can filter them out **on mainnet** as follows:

- call the the [`get_block` RPC endpoint](https://www.getmonero.org/resources/developer-guides/daemon-rpc.html#get_block) with parameter `height: 2688888`
- make sure  `result.block_header.major_version == 15`

Mainnet [parameters source](https://github.com/monero-project/monero/blob/b6a029f222abada36c7bc6c65899a4ac969d7dee/src/hardforks/hardforks.cpp#L74).

For testnet, you can use height [1982800](https://github.com/monero-project/monero/blob/b6a029f222abada36c7bc6c65899a4ac969d7dee/src/hardforks/hardforks.cpp#L101).

For stagenet, you can use height [1151000](https://github.com/monero-project/monero/blob/b6a029f222abada36c7bc6c65899a4ac969d7dee/src/hardforks/hardforks.cpp#L125).

This is pretty hacky. A cleaner solution would be nice but for the time being, I think this would be a solid help looking to the site for nodes.

**Comment by j-berman** [comment]
At this exact moment, the outdated mainnet nodes are about ~3000 blocks behind. I count 27.

**Comment by lalanza808** [comment]
Didn't see this issue, had an email from someone about the same thing; it should be resolved. I didn't add the check for `major_version` in the headers. I was under the impression any version details are not advertised by default. I'll keep it open to await confirmation of resolution without the version check.

**Comment by lalanza808** [comment]
seems resolved
