### ISSUE TITLE
Problems setting up

### ISSUE THREAD

**Issue by monerobull** [lalanza808/monero.fail#19]
I'm getting `AttributeError: 'NoneType' object has no attribute 'last_height'` when trying to set this up.
My node is using your docker-monero-node.

I'm also getting   
```
error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for py-levin
  Running setup.py clean for py-levin
Failed to build py-levin
```
When trying to make setup.
Also am unsure as to what needs to be changed in the config.py

**Comment by lalanza808** [comment]
sorry i missed this. i've got some changes coming in, i'll spend some time revamping the documentation to clear this up.

**Comment by lalanza808** [comment]
@monerobull I've update the readme and shipped some sane defaults instead of expecting people to punch them in. 

Try it out and let me know!

**Comment by lalanza808** [comment]
closing for now, lmk if still probs
