### ISSUE TITLE
Error when running prod script

### ISSUE THREAD

**Issue by ghost** [lalanza808/monero.fail#2]
Running the prod script gives the following output
```
bin/prod: line 5: .venv/bin/activate: No such file or directory
cat: data/gunicorn/gunicorn.pid: No such file or directory
Starting gunicorn with pid
```

I am not experienced with Python web servers so this may be expected, with the solution being to install some packages. If this is the case it would be beneficial to mention this in README.md (along with instructions on getting the server running such as creating config.py).

**Comment by lalanza808** [comment]
Yeah, I'll spend some more time making the tools/scripts more approachable. At this phase it's pretty rough since it's just me prototyping it out.

Will update the issue when that happens.

**Comment by lalanza808** [comment]
Duplicate from gp's issue (#5), going to go w/ that one since you ghosted me 😢
