### ISSUE TITLE
[Wownero] Display node donation address

### ISSUE THREAD

**Issue by wowario** [lalanza808/monero.fail#20]
From [v0.10.2.0](https://git.wownero.com/wownero/wownero/releases/tag/v0.10.2.0), public node operators are able to add a donation address to an `address.txt` file in the same directory as `wownerod` and announce it in RPC `get_info` call

**Comment by lalanza808** [comment]
forgot we added that functionality. beautiful. changes incoming.

**Comment by lalanza808** [comment]
added
