### ISSUE TITLE
Obsolete node URLs

### ISSUE THREAD

**Issue by boldsuck** [lalanza808/monero.fail#3]
Hi,
I completely reorganized my Monero nodes. Some URLs have changed. Can you delete them on monero.fail?
Obsolete mainnet node:
`http://lump.boldsuck.org:18081`

Obsolete stagenet nodes:
`http://crypto.boldsuck.org:38081`
`http://n452awi37fcjhxj64pox4rrtmyaambphhxlj7s5elwoqx7xfmefa4mqd.onion:38081`

Didn't find an email address, that's why I made it via Github issue. Sorry for the trouble.
Special thanks for monero.fail and xmrcannon.net.

The current nodes:
```
http://xmr-de-2.boldsuck.org:18081
http://6dsdenp6vjkvqzy4wzsnzn6wixkdzihx3khiumyzieauxuxslmcaeiad.onion:18081
http://xmr-de-1.boldsuck.org:18081
http://ip4zpbps7unk6xhlanqtw24f75akfbl3upeckfjqjks7ftfnk4i73oid.onion:18081

http://xmr-lux.boldsuck.org:38081
http://ct36dsbe3oubpbebpxmiqz4uqk6zb6nhmkhoekileo4fts23rvuse2qd.onion:38081
```

**Comment by lalanza808** [comment]
Done, thanks!
