### ISSUE TITLE
i have no idea how to launch this

### ISSUE THREAD

**Issue by Gingeropolous** [lalanza808/monero.fail#5]
So, im a dumbass and I don't really know where to start with this. I wanna run the map to see what my node sees, and I see a lot of python.

well, ima just start some random python scripts and see what happens.

**Comment by lalanza808** [comment]
yo dude, sorry it took me so long, but i wrote some docs: https://github.com/lalanza808/monero.fail/commit/a2b3d3a385f1614565db7b8dbc244460c3a0e8d7
