### ISSUE TITLE
[Feature Request] add i2p - reference included

### ISSUE THREAD

**Issue by qvqc** [lalanza808/monero.fail#6]
think this is close to whats needed, or maybe helpful reference for integration
https://git.wownero.com/qvqc/monero.fail/commit/b4008c58a217a7a8eac28260157c0a1e0bd63920

lmk if I can help, thanks!

**Comment by lalanza808** [comment]
@qvqc I've got this partially implemented on branch `i2pd` (`i2p` is my first attempt with i2p-zero). Things are mostly working app side, but I cannot seem to resolve anything over i2p. I do not know if my config/runtime stuff is borked or I just don't have any available i2p nodes. Do you have a known good node I can reach via i2p? 

I've been trying to hit these to no avail: https://github.com/monero-project/monero/blob/master/src/p2p/net_node.inl#L866-L867
and these: https://github.com/i2p-zero/i2p-zero/blob/master/mipseed.md

**Comment by lalanza808** [comment]
got this working. #26
