### ISSUE TITLE
Add an ability to download ( or view ) the raw list of monero nodes

### ISSUE THREAD

**Issue by ghost** [lalanza808/monero.fail#9]
Hello,

I just builded a parser of monero.fail to produce list of monero nodes in JSON ( and CSV ) format

https://github.com/ayanamitech/monero-fetcher

https://github.com/ayanamitech/monero-fetcher/blob/main/monero.json

https://github.com/ayanamitech/monero-fetcher/blob/main/monero.txt

It would be great if we have an API endpoint or webpage to view the raw list of servers.

Thanks!

**Comment by lalanza808** [comment]
hello, thanks for commenting. i do actually have a raw export view which you can query: https://monero.fail/nodes.json 

let me know if you may need any adjustments made to it

**Comment by ghost** [comment]
@lalanza808 Ah, that one would be better, thanks for the great service!
